%A: Between-subjects factor 'Age' with 2 levels
%B: Within-subjects factor 'Drug' with 2 levels
% Here are the data in the four conditions,
% with three Ss tested in each condition.
A1B1=[73 81 86];
A1B2=[59 67 60];
A2B1=[61 60 59];
A2B2=[63 50 61];
Y=[A1B1 A1B2 A2B1 A2B2];
B=[1 1 1 ...
   2 2 2 ...
   1 1 1 ...
   2 2 2];
A=[1 1 1 ...
   1 1 1 ...
   2 2 2 ...
   2 2 2];
S=[1 2 3 ...
   1 2 3 ...
   4 5 6 ...
   4 5 6];
nesting=[0 0 0; ... % This line indicates that factor A is not nested in any other factor.
         0 0 0; ... % This line indicates that factor B is not nested in any other factor.
         1 0 0];    % This line indicates that S (the third factor) is nested under A
                    % (the 1 in position 1 on the line indicates nesting under the first factor).
[p table stats]=anovan(Y,{A B S},...
    'model',2,...
    'random',3,...
    'nested',nesting,...
    'varnames',{'Age', 'Drug', 'Subj'});

